### CORS Preflight Request to `compare-youself`
OPTIONS https://9cxvvjl4d0.execute-api.eu-north-1.amazonaws.com/dev/compare-yourself
Accept: application/json

### POST to `compare-youself
POST https://9cxvvjl4d0.execute-api.eu-north-1.amazonaws.com/dev/compare-yourself
Content-Type: application/json
Accept: application/json

{}

