version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "compare-yourself-lambdaless"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1alt62pqr870u"
s3_prefix = "compare-yourself-lambdaless"
region = "eu-north-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "CognitoUserPoolARN=\"arn:aws:cognito-idp:eu-north-1:392971033516:userpool/eu-north-1_lhbmRfObN\""
