AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  compare-yourself-lambdaless

  SAM Template for compare-yourself-lambdaless
  
Globals:
  Function:
    Environment:
      Variables:
        COMPARE_YOURSELF_TABLE: !Ref CompareYourselfTable

Parameters:

  CognitoUserPoolARN:
    Type: String
    Description: ARN of Cognito User Pool
    Default: arn:aws:cognito-idp:eu-north-1:392971033516:userpool/eu-north-1_lhbmRfObN

Resources:

  CompareYourselfRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name: compare-yourself-lambdaless
      Description: Compare Yourself API Lambdaless
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: compare-yourself-lambdaless-Prod-oas30-apigateway.yaml

  CompareYourselfTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: UserId
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  CompareYourselfAPIGatewayRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
      Policies:
        - PolicyName: CompareYourselfAPIDynamoDBPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:PutItem'
                  - 'dynamodb:Scan'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:DeleteItem'
                # Including * in the resource Arn allows access to the DynamoDB table and indexes
                Resource: !Sub
                  - '${varTableArn}*'
                  - varTableArn: !GetAtt CompareYourselfTable.Arn

Outputs:
  CompareYourselfRestApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${CompareYourselfRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/compare-yourself"

