AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  compare-yourself

  Sample SAM Template for compare-yourself
  
Globals:
  Function:
    Timeout: 3
    CodeUri: app-code/
    Runtime: nodejs14.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        COMPARE_YOURSELF_TABLE: !Ref CompareYourselfTable

Resources:

  CompareYourselfRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name: compare-youself
      Description: Compare Yourself API
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: compare-yourself-Prod-oas30-apigateway.yaml

  StoreDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: store-data.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CompareYourselfTable
      Events:
        StoreData:
          Type: Api
          Properties:
            RestApiId: !Ref CompareYourselfRestApi
            Path: /compare-yourself
            Method: post

  DeleteDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: delete-data.handler
      Events:
        DeleteData:
          Type: Api
          Properties:
            RestApiId: !Ref CompareYourselfRestApi
            Path: /compare-yourself
            Method: delete

  GetDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get-data.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref CompareYourselfTable
      Events:
        GetData:
          Type: Api
          Properties:
            RestApiId: !Ref CompareYourselfRestApi
            Path: /compare-yourself/{type}
            Method: get

  CompareYourselfTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: UserId
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  CompareYourselfRestApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${CompareYourselfRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/compare-yourself"

