AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  compare-yourself

  Sample SAM Template for compare-yourself
  
Globals:
  Function:
    Timeout: 3

Resources:

  CompareYourselfRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name: compare-youself
      Description: Compare Yourself API
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: compare-yourself-Prod-oas30-apigateway.yaml

  StoreDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app-code/
      Handler: store-data.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        StoreData:
          Type: Api
          Properties:
            RestApiId: !Ref CompareYourselfRestApi
            Path: /compare-yourself
            Method: post

  DeleteDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app-code/
      Handler: delete-data.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        DeleteData:
          Type: Api
          Properties:
            RestApiId: !Ref CompareYourselfRestApi
            Path: /compare-yourself
            Method: delete

  GetDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app-code/
      Handler: get-data.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        GetData:
          Type: Api
          Properties:
            RestApiId: !Ref CompareYourselfRestApi
            Path: /compare-yourself/{type}
            Method: get

Outputs:
  CompareYourselfRestApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${CompareYourselfRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/compare-yourself"

